export interface Lesson { id: string; title: string; module: string; topic: string; level: number; minutes: number; summary: string; objectives: string[]; sections: { title: string; text: string; code: string }[]; challengeIds: string[] }
export interface Question { id: string; lessonId: string; topic: string; prompt: string; options: string[] }
export interface Challenge { id: string; title: string; description: string; lessonId: string; topic: string; library: string; kind: string; difficulty: string; functionSignature: string; inputSchema: Record<string, string>; outputSchema: string; ordering: string; starterCode: string; visibleDataset: Record<string, unknown>[]; hints: string[]; timeLimit: number; memoryLimit: number }
export interface Project { id: string; title: string; description: string; tasks: string[]; challengeIds: string[]; files: string[]; rubric: string[] }
export interface Exam { id: string; title: string; questionIds: string[]; challengeIds: string[] }
export interface Catalog { version: string; lessons: Lesson[]; questions: Question[]; challenges: Challenge[]; projects: Project[]; exams: Exam[] }
export interface Session { email: string | null; demo: boolean; placement: string; dailyMinutes: number }
export interface Progress { completed: Record<string, string[]>; quizAccuracy: number; questionsAnswered: number; skills: { topic: string; score: number; available: boolean; theoryCount: number; challengeCount: number }[]; mistakes: { contentId: string; topic: string; kind: string; failures: number; resolved: boolean; due: string; ready: boolean; timestamp: string }[]; bookmarks: string[]; weekly: { attempts: number; passed: number; lessons: number }; activity: Record<string, number>; currentLevel: string; recentAttempts: { id: number; contentId: string; kind: string; correct: boolean; createdAt: string }[] }
export interface Feedback { correct: boolean; yourAnswer: string; correctAnswer: string; explanation: string; correctExplanation: string; example: string; lessonId: string; attemptNumber: number }
export interface Frame { columns: string[]; data: unknown[][] }
export interface Output extends Partial<Frame> { type: string; data?: unknown[][]; title?: string; xlabel?: string; ylabel?: string; lines?: { x: string[]; y: number[] }[] }
export interface Grade { status: string; submitted: boolean; tests: { hidden: boolean; passed: boolean; category: string; feedback: string }[]; visibleTestsPassed: number; hiddenTestsPassed: number; duration: number; stdout: string; stderr: string; output?: Output; expected?: Frame }
